<a href="https://colab.research.google.com/github/adlinfahreza18/dm_tugas_1/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sebelum memulai preprocessing kita perlu meng-import library-library yang akan digunakan. Library numpy digunakan untuk melakukan komputasi matriks. Matplotlib digunakan untuk visualisasi data seperti grafik atau plot. Pandas digunakan untuk mendownload open source Python package.

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Deklarasi variabel-variabel. Variabel dataset digunakan untuk mengambil file csv. Pada file tersebut terdapat kolom-kolom atribut dan label. Variabel att digunakan untuk menampung kolom-kolom atribut yaitu 3 kolom pertama sedangkan lbl untuk kolom label atau target yaitu sisanya. 

In [23]:
dataset = pd.read_csv('Data.csv')
att = dataset.iloc[:, :-1].values
lbl = dataset.iloc[:, -1].values

Print untuk mengetahui apakah variabel-variabel diatas berfungsi normal.

In [24]:
print(att)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [25]:
print(lbl)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Pada hasil print diatas terdapat beberapa missing value yang ditandai 'nan'. Untuk menghilangkan nilai nan tersebut kita bisa menggunakan imputer dengan metode mean yaitu mengganti 'nan' tersebut dengan nilai rata-rata.

In [27]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(att[:, 1:3])
att[:, 1:3] = imputer.transform(att[:, 1:3])

In [28]:
print(att)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Disini kita sudah berhasil menghilangkan missing value.

Sekarang kita perlu mengubah menjadi bentuk matriks menggunakan ColumnTransformer dan OneHotEncoder.

In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
att = np.array(ct.fit_transform(att))

In [31]:
print(att)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [32]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
lbl = le.fit_transform(lbl)

In [33]:
print(lbl)

[0 1 0 0 1 1 0 1 0 1]


In [34]:
from sklearn.model_selection import train_test_split
att_train, att_test, lbl_train, lbl_test = train_test_split(att, lbl, test_size=0.2, random_state=1)

In [35]:
print(att_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [36]:
print(att_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [37]:
print(lbl_train)

[0 1 0 0 1 1 0 1]


In [38]:
print(lbl_test)

[0 1]


In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
att_train[:, 3:] = sc.fit_transform(att_train[:, 3:])
att_test[:, 3:] = sc.transform(att_test[:, 3:])

In [40]:
print(att_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [41]:
print(att_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
