In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("satisfaction.csv") # Airline Passenger Satisfaction Dataset
df.head(10)

id  Gender Customer Type  Age Type of Travel     Class  \
0   70172    Male         Loyal   13       Personal  Eco Plus   
1    5047    Male      Disloyal   25       Business  Business   
2  110028  Female         Loyal   26       Business  Business   
3   24026  Female         Loyal   25       Business  Business   
4  119299    Male         Loyal   61       Business  Business   
5  111157  Female         Loyal   26       Personal       Eco   
6   82113    Male         Loyal   47       Personal       Eco   
7   96462  Female         Loyal   52       Business  Business   
8   79485  Female         Loyal   41       Business  Business   
9   65725    Male      Disloyal   20       Business       Eco   

   Inflight wifi service  Departure/Arrival time convenient  \
0                      3                                  4   
1                      3                                  2   
2                      2                                  2   
3                      2                                  5   
4                      3                                  3   
5                      3                                  4   
6                      2                                  4   
7                      4                                  3   
8                      1                                  2   
9                      3                                  3   

   Ease of Online booking  Gate location  ...  Online boarding  Seat comfort  \
0                       3              1  ...                3             5   
1                       3              3  ...                3             1   
2                       2              2  ...                5             5   
3                       5              5  ...                2             2   
4                       3              3  ...                5             5   
5                       2              1  ...                2             1   
6                       2              3  ...                2             2   
7                       4              4  ...                5             5   
8                       2              2  ...                3             3   
9                       3              4  ...                3             3   

   Inflight entertainment  On-board service  Leg room service  \
0                       5                 4                 3   
1                       1                 1                 5   
2                       5                 4                 3   
3                       2                 2                 5   
4                       3                 3                 4   
5                       1                 3                 4   
6                       2                 3                 3   
7                       5                 5                 5   
8                       1                 1                 2   
9                       2                 2                 3   

   Baggage handling  Checkin service  Inflight service  Cleanliness  \
0                 4                4                 5            5   
1                 3                1                 4            1   
2                 4                4                 4            5   
3                 3                1                 4            2   
4                 4                3                 3            3   
5                 4                4                 4            1   
6                 4                3                 5            2   
7                 5                4                 5            4   
8                 1                4                 1            2   
9                 4                4                 3            2   

   satisfaction  
0  Dissatisfied  
1  Dissatisfied  
2     Satisfied  
3  Dissatisfied  
4     Satisfied  
5  Dissatisfied  
6  Dissatisfied  
7     Satisfied  
8  Dissatisfied  
9  Dissatisfied  

[10 rows x 21 colum

In [23]:
x = df.iloc[:, 1:20].values
y = df.iloc[:, -1].values 

In [3]:
# ENCODING

# OneHotEncoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0,1,3,4])], remainder= "passthrough")
x = np.array(ct.fit_transform(x))
print(x)

# Label Encoding
from sklearn.preprocessing import LabelEncoder
ls = LabelEncoder()
y = ls.fit_transform(y)
print(y)

[[0.0 1.0 0.0 ... 4 5 5]
 [0.0 1.0 1.0 ... 1 4 1]
 [1.0 0.0 0.0 ... 4 4 5]
 ...
 [0.0 1.0 1.0 ... 5 5 4]
 [1.0 0.0 1.0 ... 5 4 1]
 [0.0 1.0 0.0 ... 4 3 1]]
[0 0 1 ... 0 0 0]


In [4]:
# SPLIT DATA INTO TRAIN AND TEST SET

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 0)

In [5]:
print("test_size: ", len(x_test)/len(df))
print("x_test: ", len(x_test))

test_size:  0.30000769941484445
x_test:  31172


In [6]:
# FEATURE SCALING

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [7]:
print(x_train, x_test)

[[ 0.98610001 -0.98610001 -0.47229746 ... -1.81878362 -1.39191808
  -0.98246286]
 [-1.01409593  1.01409593 -0.47229746 ... -0.23982266  0.30650383
  -0.21919377]
 [ 0.98610001 -0.98610001 -0.47229746 ...  0.54965782  0.30650383
  -0.21919377]
 ...
 [-1.01409593  1.01409593 -0.47229746 ... -0.23982266  0.30650383
  -0.21919377]
 [ 0.98610001 -0.98610001 -0.47229746 ...  0.54965782  1.15571479
   1.3073444 ]
 [ 0.98610001 -0.98610001 -0.47229746 ...  0.54965782  0.30650383
  -0.98246286]] [[-1.01409593  1.01409593 -0.47229746 ...  0.54965782  0.30650383
  -0.21919377]
 [ 0.98610001 -0.98610001 -0.47229746 ...  1.3391383  -1.39191808
   1.3073444 ]
 [-1.01409593  1.01409593 -0.47229746 ... -1.02930314  0.30650383
  -1.74573194]
 ...
 [ 0.98610001 -0.98610001  2.1173097  ...  1.3391383   1.15571479
  -1.74573194]
 [-1.01409593  1.01409593 -0.47229746 ... -0.23982266  0.30650383
   1.3073444 ]
 [-1.01409593  1.01409593 -0.47229746 ... -1.02930314 -1.39191808
  -0.21919377]]


In [20]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 13, metric = 'euclidean', p = 2)
classifier.fit(x_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=13)

In [21]:
y_pred = classifier.predict(x_test)

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
acc_score = accuracy_score(y_test, y_pred)
print("acc: ",round(acc_score*100,2))

acc:  93.01
